# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb7504e7f1a01d13cdb0f7277e4a8f6ef64597294aff93f56874ee66e05b84d7ceb95f8babeb9e9eba854b425c1e8aa613e5af18517082f3cda5142a33336eb

test:
  secret_key_base: 53210ce8acd6e95fb42ab3aef6b91d605fadf48d9f968883b8d3557b1001533142727912a08e8b53ce1e64aca9b465084ad542e49cc4fe097588fad9c673f5e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
